### PR TITLE
Homepage using Yeoman

### PR DESCRIPTION
**Pull request by grprtkal**
Hi @KirstieJane, 

I've created the homepage using Yeoman. To see this locally, you can follow the instructions here for installation. http://yeoman.io/learning/index.html

I also found the tutorial helpful to understand how things work. http://yeoman.io/codelab/index.html

After installing yeoman, in order to run the app locally, you'll need to use "grunt serve" in terminal and the page should show up in localhost:9000/#/. You should be able to preview it in your browser.

I also noticed that some of your folders from gh-pages (like javascripts folder) are not showing up on my branch. I have no idea why :/ Before you merge anything, please make sure I didn't accidentally remove some of your documents! 

Let me know if you have any questions :) 

Cheers,
Gurpreet

### CODE REVIEW

**Comment by KirstieJane** [comment]
This is great @grprtkal! I'm in Berlin at the Mozilla Retreat planning MozFest (to be held in London in October) but I'll get this downloaded and checked over the weekend. Really excited to have a new home page :smiley:

**Comment by KirstieJane** [comment]
Ok - so I've installed `yo`, `grunt` and `karma` all with:

```
npm install yo
npm install -g grunt-cli
npm install karma
```

Then I ran `grunt serve` from inside the `STEMMRoleModels` folder locally, and opened up a browser window at `localhost:9000` and low and behold, there's our lovely website!

Thank you @grprtkal!

Now, the question I have is what will happen when I merge this? Will it just replace the current page that [stemmrolemodels.com](stemmrolemodels.com) points to?

And, as I click around, I realise that we need a home button somewhere on the page. Maybe in the top left? I think "contribute" could move to the footer perhaps?

**Comment by Ryuno-Ki** [comment]
> Now, the question I have is what will happen when I merge this? Will it just replace the current page that stemmrolemodels.com points to?

Well, according to WHOIS database look up, you set up that website, @KirstieJane. How did you do that?

My guess is: It will.

Since when you open the [associated github.io URL](https://kirstiejane.github.io/STEMMRoleModels) you get redirected to http://stemmrolemodels.com (and loose HTTPS).

> And, as I click around, I realise that we need a home button somewhere on the page.

On http://stemmrolemodels.com/site/allaboutus.html the "**STEMM Role Models**" already links back to the home.

**Comment by grprtkal** [comment]
Hey @KirstieJane,

Before you merge, you can make a back up branch that has all your existing code. That way, if anything goes unexpected, you still have everything you need for the current site. 

My pull request doesn't have some of the content you have on gh-pages branch like the sites folder which has the HTML of some of your pages. 

I'm not 100% sure how the current site was created and all the files involved. One possible approach would be if you picked out the folders that you need for the creation of http://stemmrolemodels.com and added it to what I currently have in this pull request. 

Hope that helps! :)

**Comment by KirstieJane** [comment]
So sorry for the delay getting back to you @grprtkal! What I'd really love is for the two pages to exist side by side. At the moment www.stemmrolemodels.com points to `index.html` in the `gh-pages` branch of this repo. Would it be possible for your homepage to be called something like `index2.html`?

The reason I don't want to just get rid of the current page is that - as you said - your site doesn't have the content yet. In my head I'm imagining merging the PR and adding a link to the current `index.html` page to link to the "new site under development".

Does any of this make sense? @acabunoc & @auremoser - maybe you have some language that can help me out!

**Pull request merged**
