### PR TITLE
Update UsingGoogleTagManager.md

### PR DESCRIPTION
**Pull request by amitkumarj441**
Added few necessary info related to GTM.

### CODE REVIEW

**Comment by KirstieJane** [comment]
Thanks @amitkumarj441! I'm not sure how this fits with the pull request creating the How_GTM_works documentation (#41). It doesn't seem like we need two separate pieces of documentation.

There are also a couple of grammatical errors:
- sites on your site --> sits on your site
- holds your accounts information --> holds your account's information

As I said in my comment to #39 - I don't have the expertise to review this without any additional links etc. @grprtkal may be able to take a look, but I think sorting out the fact that we have two different documents is the first priority!

**Comment by amitkumarj441** [comment]
Hi @KirstieJane , Like as i said earlier in #41 that I've to merge this current commit #39 .
Should i close this pull request #39 after merging into #41 .

**Comment by KirstieJane** [comment]
Heya @amitkumarj441 - I've closed this pull request as it's all in line with #41 :)

**Comment by amitkumarj441** [comment]
Thanks @KirstieJane for closing irrelevant pull requests!

**Pull request closed without merging**
