### PR TITLE
Removes speaker bio from views, data, and model

### PR DESCRIPTION
**Pull request by deniederhut**
Changes the html index, and js app and helper file to remove speaker bio from web views.

### CODE REVIEW

**Comment by KirstieJane** [comment]
Thanks @deniederhut!

Is bio gone completely? Is it still in the google form or are we dropping it all together?

**Comment by deniederhut** [comment]
Hi @KirstieJane ! It's still there in the forms and datasheet - I (or anyone, really) can remove them after the pull request is merged.

**Comment by KirstieJane** [comment]
Megastar - just wanted to clarify that the plan was to remove bio completely.
Meeeerged :smile:

**Comment by deniederhut** [comment]
Megathanks! Bio question removed from form and data sheet. We'll need to
find another way to tell the world I love coladas and rain.

**Pull request merged**
