### PR TITLE
Update Why_Yeoman.md

### PR DESCRIPTION
**Pull request by amitkumarj441**
Updated Why_Yeoman.
Review needed.

### CODE REVIEW

**Comment by KirstieJane** [comment]
Hi @amitkumarj441 - can you merge your comments into @jvoytek's (which are now part of master) and resubmit the pull request please.

Thanks again for the hard work.

**Comment by amitkumarj441** [comment]
Hi @KirstieJane , Yes. I can
I'll do it now itself.

**Comment by KirstieJane** [comment]
Hi @amitkumarj441 - is this pull request redundant now that you've made #45? Can you close it if so?

Thank you!

**Comment by amitkumarj441** [comment]
Hi @KirstieJane ,
Thanks for pointing out!

Cheers,
Amit Kumar Jaiswal

**Pull request closed without merging**
