### PR TITLE
Create How_GTM_works

### PR DESCRIPTION
**Pull request by amitkumarj441**
Added requisite info related to GTM.

### CODE REVIEW

**Comment by KirstieJane** [comment]
Thanks for creating this @amitkumarj441! I have to admit, I don't have the expertise to check what you've written. @grprtkal - would you be able to take a look through and comment?

One way to make the documentation easier to read would be to add in some links that go to the Google Tag Manager documentation that I can follow to verify what's going on!

Another point is that this file doesn't define GTM anywhere! That needs to be included somewhere near the beginning! :smiley: 

What's the difference between this and the pull request (#39) that's updating the UsingGoogleTagManager.md wiki doc?

Thanks for all the work getting this documentation in place! STEMM Role Models of the future will really appreciate it!

**Comment by amitkumarj441** [comment]
Hi @KirstieJane ,
I defined GTM in pull request (#39) , so it would be better if we keep only one master GTM document instead of these two. But before that I've to merge #39  into #41

**Comment by grprtkal** [comment]
Hi @KirstieJane and @amitkumarj441, 

I can help to look over this pull request. @amitkumarj441, I really like this as a starting point. I think it would be helpful to outline the steps it takes to add a tag in Google Tag Manager. This can help new contributors to add events for tracking fairly quickly. We could add a section on "How to track an event in analytics using GTM." I think our focus should be on how to get someone up and running in GTM fast rather than purely on GTM terminology which may cause confusion and deter people from contributing.  I will add more detailed comments soon. Thank you!

**Comment by amitkumarj441** [comment]
Hi @KirstieJane ,
Why did you closed this pull request #41 . It would be better if @grprtkal review this pull request, I think she's busy this weekend.

Cheers,
Amit Kumar Jaiswal

**Comment by KirstieJane** [comment]
Sorry @amitkumarj441! It closed because I got rid of the master branch!! I didn't realise that would happen. Can you create a new pull request against the gh-pages branch that's left?

Really sorry again, I didn't mean to close it! :cry:

**Comment by amitkumarj441** [comment]
Hi @KirstieJane ,
It's okay! I'm gonna creating a new pull request for the same. But I request you to please remind @grprtkal for this as she already committed for her upcoming views & comments over this pull request.
Hope you consider this.

Cheers,
Amit Kumar Jaiswal

**Comment by grprtkal** [comment]
Hi @amitkumarj441 and @KirstieJane, 

I'm still committed to providing more detailed comments on this pull request. I'm fine with @amitkumarj441 creating a new one and I can comment on that one. Apologies for delay. I work full time so can only provide feedback on weekends. I expect to provide more detailed comments by early next week.  

Thanks, 
Gurpreet

**Pull request closed without merging**
