### PR TITLE
Further navbar fixes

### LINKED ISSUE #106: Nav bar doesn't work on mobile
So saaaad!

I can see the nav-bar but when I click on it it doesn't show me anything.

If anyone knows why please comment!

### PR DESCRIPTION
**Pull request by stain88**
Hopefully fixes #106 
Also changed paths to being root relative, so any further changes to navbar or footer can just be directly copied across pages.

### CODE REVIEW

**Comment by stain88** [comment]
Hmm, looks like I've accidentally merged "fixes" for #109 and #99 in this too

**Comment by KirstieJane** [comment]
Hi @stain88 - thanks for this - I have to say, lining up the indentations etc makes me so so happy!

Unfortunately, making the branches root relative doesn't work here. What should be https://stain88.github.io/STEMMRoleModels/index.html becomes https://stain88.github.io/index.html or https://stain88.github.io/STEMMRoleModels/site/search_database.html becomes https://stain88.github.io/site/search_database.html.

I think it also breaks the connection to the stylesheets...

**Comment by KirstieJane** [comment]
Great - thanks @stain88 - I was going to ask why those changes were there - I hadn't realised they were addressing #99 and #109 :smile:

**Comment by stain88** [comment]
Hmm, looks like i need to learn more about gh-pages then...
Wonder if that would still be broken on stemmrolemodels.com. Anyway, I'll revert those paths.

**Comment by KirstieJane** [comment]
Yes - I thought the same thing - but it's so mega convenient to be able to check branches in pull requests that I'd rather the gh-pages branches still worked :smile:

Totally followed the logic though!

**Comment by stain88** [comment]
Ok, that should be all of them

**Comment by KirstieJane** [comment]
Looks great! Thank you @stain88!!

**Pull request merged**
