### PR TITLE
Update contact.html

### PR DESCRIPTION
**Pull request by amitkumarj441**
link updated #86

### CODE REVIEW

**Comment by KirstieJane** [comment]
Hi @amitkumarj441! Sorry for the slow reply. I don't think linking to my personal website is necessary for the STEMM Role Models project. However, if you wanted to add in our twitter link to this page that would be great!

**Comment by amitkumarj441** [comment]
@KirstieJane It's okay! I just added our STEMMRoleModels twitter link. Please have a look into it.

**Comment by KirstieJane** [comment]
Hi @amitkumarj441 - thank you for making the change. Unfortunately the link doesn't make sense anymore!

What I had meant was that we could add in a line that let people know that they could contact us via twitter. Maybe at the end of the page it could say:

> Please follow us on twitter!

And then you could put in the STEMM Role Models twitter link there.

Does that make sense?

Don't link to my name for the moment - having my email there is fine.

Thank you!

**Comment by amitkumarj441** [comment]
Hey @KirstieJane ,

Thanks for pointing out! I just re-edited those things, Please have a look into my PR.'

Cheers,
Amit Kumar Jaiswal

**Comment by KirstieJane** [comment]
Hi @amitkumarj441 - the sentence makes even less sense now! Take a deep breath and make sure that what you've committed would look good to new visitors to the site.

Follow us on twitter needs to be a separate line to that which points out how to contact me by email.

Here's a suggestion for text. But it needs to have the appropriate links added.

> This is the page that explains how to contact us.
> 
> If you'd like to know more about the project you can join either (or both) of our mailing lists:
> 
> Click here to follow our project updates.
> 
> Click here to join our development mailing list and contribute to the open source development of the project on GitHub.
> 
> You can contact the lead developer Kirstie Whitaker via email at kw401 AT cam DOT ac DOT uk.
> 
> You're always welcome to check out the GitHub repository of the STEMM Role Models project at www.GitHub.com/KirstieJane/STEMMRoleModels and to join in the discussion in our Gitter chat room.
> 
> We'd love for you to follow us on twitter and tell all your friends!

**Comment by KirstieJane** [comment]
Thanks @amitkumarj441! Merged! :tada: :cake: :balloon:

**Pull request merged**
