### PR TITLE
A quick working site using Yeoman and the angular-fullstack generator.

### PR DESCRIPTION
**Pull request by jvoytek**
So there's a lot here, and definitely more than is necessary for a simple content-only site, but as an app development framework, I like it. There are lots of configurable parts, for example I chose to write the html templates in Jade, but you can configure it to use straight html. Similarly I chose the Mocha Chai unit-testing route but you can choose Jasmine instead. You can also stub out a simple authentication system (which I did not do). So, really this probably isn't a real starting point but it was a good exercise. If anyone wants to play around with creating pages, branch it and check out the README file. You can get more information about the angular-fullstack generator commands here: https://github.com/angular-fullstack/generator-angular-fullstack

### CODE REVIEW

**Comment by grprtkal** [comment]
Hi @jvoytek and @KirstieJane, 
If I want to checkout this PR locally just to try it out and play around with it, how would I go about doing that? 

I tried: 
   git fetch origin pull/53/head:pr-53
   git checkout pr-53

However, that didn't seem to work. Any advice? :)

**Comment by jvoytek** [comment]
Hmm, I am less familiar with the repository owner side of GitHub but I found this help page which says there should be a cheat sheet of git commands for getting a pull request locally at the bottom of a pull request page, "At the bottom of the pull request, click command line. Follow the sequence of steps to bring down the proposed pull request." 

https://help.github.com/articles/checking-out-pull-requests-locally/

It doesn't seem to indicate that pr's from a fork would need any special permission but let me know if there's something I need to do to the fork to allow it...

**Comment by jvoytek** [comment]
You know you could also just fork my fork and play with it that way...

https://github.com/jvoytek/STEMMRoleModels

**Comment by KirstieJane** [comment]
Hey @jvoytek and @grprtkal! Thank you @jvoytek for putting this together!! The difficulty is that you've gone waaaay beyond what I can review and manage. Is there any chance we could chat on skype or gchat or whatever to see if I can get up to speed?

And to @grprtkal - I think forking from Jess' version of the repo is the easiest thing to do...although I know that could get pretty messy.

**Comment by grprtkal** [comment]
Thanks for the advice @jvoytek and @KirstieJane. I have an instance of Yeoman running now :)

**Comment by Ryuno-Ki** [comment]
Hey, @grprtkal,

would you mind to explain how you did that in the end?
Could be written down in [CONTRIBUTING.md](https://github.com/KirstieJane/STEMMRoleModels/blob/d1c5d38844c823fa5f6cd994ed6662542ea32116/CONTRIBUTING.md) then.

**Comment by Ryuno-Ki** [comment]
Personally I'm preferring [peg-markdown](https://github.com/jgm/peg-markdown) when translating Markdown files to HTML.

When I prototype in HTML, I'm using [HAML](http://haml.info/tutorial.html). It depends on what you want to achieve. There are [plenty of Static Site Generators](https://staticsitegenerators.net/) out there.

Concerning AngularJS: To me, it's overblown if you just want to get content online. You can use it when you need that content to become _fancy_. I can help with that (to a certain degree) :-)

**Comment by grprtkal** [comment]
Hi @Ryuno-Ki, 

I ended up cloning @jvoytek's fork at https://github.com/jvoytek/STEMMRoleModels and playing around with it locally. I can add it to Contribute.md. It could be useful for Step 2 ("Making a change"), though I'll try to make the verbiage simple so as to not confuse people even more. 

And regarding Angular, I agree if it's just a matter of content, then simple HTML is fine especially for rapid prototyping; however, when we have real users and we want their profiles to be retrieved from a database, the data-binding capabilities of Angular can be really useful. 

If we want to keep things really simple, for the first 5 - 10 users, once they submit their info using the sign up form, we can manually input their profile info on the webpage using static HTML. That's another option.

**Comment by KirstieJane** [comment]
Hey @jvoytek @grprtkal @Ryuno-Ki - I really appreciate all the work that has gone into this pull request, but I've had a few great discussions that have generally concluded that it's too complicated for the build of the MVP that is our current goal. I've found that I've become a huge bottleneck because I can't review the code.

That's not to say that we won't use more complex frameworks in the future - but at the moment the google sheets database and the combination of HTML, CSS and bootstrap works well enough.

This summer's motto is KISS ;) :kiss: :kissing_heart: 

But seriously thank you for all the work, sorry to not merge it all!

**Pull request closed without merging**
